Using Rails Form Helpers
didymus707/re-former pull request #1
Opened 2020-06-02 23:01 UTC by didymus707

- Form helpers such as Form_tag and Form_for were used in building rails forms in this commit
- Also, a plain html form was also built too

2020-06-03 15:19 UTC, shshamim63 requested changes
## Status :recycle: Changes Required :1234: 
___
Hi @didymus707 :wave: 
Almost there to complete this project. But there are some issues that are blocking me to approve it right now. Let's get to them.
___
### :spades: Mandatory Changes :spades: 
___
1. It seems the readme is containing the basic info which is provided when creating a rails app. The info required for this project is not it. Please generate descriptive readme with the project setup and how to use it related info.
2. While I tried to update a info it throws error related to the path. If you need to perform an edit operation it should pass through two consecutive actions, edit and update. I can only see the path related to edit. Where is the update route and action? Please fix the route and add an action in the user controller related to update.
![image](https://user-images.githubusercontent.com/38625956/83654697-44df5b00-a5df-11ea-9dc2-b0a74c5ab540.png)
___
### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-06-03 15:19 UTC, shshamim63 commented on app/views/users/edit.html.erb
> +<%= form_for @user, url: {action: 'edit'} do |f| %>
When editing an entry the corresponding next action should be 'update'. But you have defined edit. That's why, when I try to entry it throws an error related to the path. To fix it 
```ruby
<%= form_for @user do |f| %>
```
Rails is smart enough to find the update path when in terms of the edit.

2020-06-03 22:45 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Lets give this project a proper title in the readme file.
- [x]  I can't see any button to enable me edit `User`
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-06-03 22:45 UTC, kobiyoyo commented on app/views/users/new.html.erb
> +<form accept-charset="UTF-8" action="/users" method="post">
Its better written this way `<form action=users_path method='post' accept-charset="UTF-8">`

2020-06-03 22:45 UTC, kobiyoyo commented on app/views/users/new.html.erb
> +<%# <%= form_tag('/users') do %>
Its better written this way `<%= form_tag(users_path) do |f|%>`

2020-06-04 19:43 UTC, mosesogwo approved these changes
**Hello:clap:. Congratulations :+1:. Your project is approved.**

You can now merge this PR.

**Cheers :stars:**

### Status: Approved:heavy_check_mark:

2020-06-04 19:48 UTC, merged